// Regenerates the "Portfolio snapshot" block in README.md from the committed
// data (book.json + trades.csv + marks.csv). The heartbeat runs this each cycle
// so the README is a live read of the book without opening Robinhood. Pure
// reads + one file write; reuses the same loaders the engine uses.
//
// CLI: bun run snapshot   (writes README.md between the SNAPSHOT markers)

import { readFileSync, writeFileSync } from "node:fs";
import { validateBook } from "./validate";
import { loadTrades, computeStats, computeLaneStats } from "./stats";
import { loadMarks, computeGate } from "./gate";
import { MAX_POSITIONS } from "./risk";

const ROOT = new URL("../../", import.meta.url).pathname;
const DATA = ROOT + "robinhood-agentic/data/";
const README = ROOT + "README.md";
const START = "<!-- SNAPSHOT:START -->";
const END = "<!-- SNAPSHOT:END -->";

function buildSnapshot(asOfDate: string): string {
  const book = validateBook(JSON.parse(readFileSync(DATA + "book.json", "utf8")));
  const trades = loadTrades(DATA + "trades.csv");
  const stats = computeStats(trades, { asOf: asOfDate });
  const contrib = (book as { contributions?: number }).contributions ?? 0;
  const profit = book.accountValue - contrib;
  const ret = contrib ? (profit / contrib) * 100 : 0;
  const usd = (n: number) => "$" + n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  const bookRisk = book.positions.reduce((s, p) => s + (p.stop == null ? 0 : Math.max(0, (p.entry - p.stop) * p.qty)), 0);

  const L = (s: string) => lines.push(s);
  const lines: string[] = [];
  L(`_As of ${book.asOf ?? asOfDate} — auto-generated by the trading loop (\`bun run snapshot\`). Source of truth is Robinhood; this is the committed mirror._`);
  L("");
  if (contrib) {
    L(`**Invested ${usd(contrib)} · Current ${usd(book.accountValue)} · Profit ${profit >= 0 ? "+" : "-"}${usd(Math.abs(profit))} (${ret >= 0 ? "+" : ""}${ret.toFixed(1)}%)**`);
  } else {
    L(`**Current ${usd(book.accountValue)}**`);
  }
  L("");
  L(`Settled cash ${usd(book.cash)} · ${book.positions.length}/${MAX_POSITIONS} slots · open risk to stops ${usd(bookRisk)} (${((bookRisk / book.accountValue) * 100).toFixed(1)}%)`);
  L("");
  L("| Position | Qty | Entry | Stop | Mark | P&L | Theme |");
  L("|---|--:|--:|--:|--:|--:|---|");
  for (const p of book.positions) {
    const mark = p.price ?? p.entry;
    const pl = ((mark / p.entry - 1) * 100);
    const stop = p.stop == null ? "—" : p.stop.toFixed(2) + (p.stop > p.entry ? " (locked)" : p.stop === p.entry ? " (BE)" : "");
    L(`| ${p.symbol} | ${p.qty} | ${p.entry.toFixed(2)} | ${stop} | ${mark.toFixed(2)} | ${pl >= 0 ? "+" : ""}${pl.toFixed(1)}% | ${(p as { theme?: string }).theme ?? ""} |`);
  }
  L("");

  // closed trades
  const closed = trades.filter((t) => t.exit_date !== "");
  if (closed.length) {
    L("Closed trades:");
    L("");
    L("| Trade | Lane | R | P&L |");
    L("|---|---|--:|--:|");
    for (const t of closed) L(`| ${t.trade_id} | ${t.lane} | ${t.r_multiple?.toFixed(2) ?? "?"}R | $${t.pnl_usd?.toFixed(2) ?? "?"} |`);
    L("");
  }

  // §6a scoreboard + per lane
  const f = (n: number | null) => (n == null ? "n/a" : n.toFixed(2));
  const lanes = [...computeLaneStats(trades, { asOf: asOfDate })].map(([ln, s]) => `${ln} ${f(s.expectancyR)}R (${s.closedCount} closed)`).join(" · ");
  L(`**Measurement gate (POLICY §6a):** ${stats.closedCount} closed / ${stats.openCount} open · expectancy ${f(stats.expectancyR)}R · capital-add ${stats.gate.eligibleForCapitalAdd ? "ELIGIBLE" : "not eligible"} (needs ≥10 closed / >+0.25R / 0 breaches / ≥4wk). Per lane: ${lanes}.`);

  // regime gate
  try {
    const g = computeGate(loadMarks(DATA + "marks.csv"), asOfDate);
    if (g.status === "ok") L(`\n**Lane-2 regime gate:** ${g.gate} (QQQ ${g.qqqClose.toFixed(2)} vs ${g.maLen}d MA ${g.ma.toFixed(2)}, as of ${g.asOf}).`);
  } catch {
    // marks unreadable → omit gate line
  }
  return lines.join("\n");
}

if (import.meta.main) {
  const asOf = process.argv[2] ?? new Date().toISOString().slice(0, 10);
  const block = buildSnapshot(asOf);
  const readme = readFileSync(README, "utf8");
  if (!readme.includes(START) || !readme.includes(END)) {
    console.error(`README.md is missing the ${START} / ${END} markers — add them once, then re-run.`);
    process.exit(1);
  }
  const next = readme.replace(new RegExp(`${START}[\\s\\S]*${END}`), `${START}\n${block}\n${END}`);
  writeFileSync(README, next);
  console.log("README snapshot updated.");
}
